services:
  app:
    image: ghcr.io/stackblitz-labs/bolt.diy:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - COMPOSE_PROFILES=production
      - PORT=5173
      - GROQ_API_KEY=${GROQ_API_KEY}
      #- HuggingFace_API_KEY=${HuggingFace_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      #- GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
     # - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      #- XAI_API_KEY=${XAI_API_KEY}
      #- TOGETHER_API_KEY=${TOGETHER_API_KEY}
      #- TOGETHER_API_BASE_URL=${TOGETHER_API_BASE_URL}
     # - AWS_BEDROCK_CONFIG=${AWS_BEDROCK_CONFIG}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-info}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      - RUNNING_IN_DOCKER=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: pnpm run dockerstart
    networks:
      - bolt-network
    # Remove any port mapping - nginx will handle external access

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "5173:80"  # This is the port Dokploy will use
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./auth/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - app
    networks:
      - bolt-network

networks:
  bolt-network:
    driver: bridge
